"""Build REVIEWS.pdf — the N-paper QN paper-audit showcase report.

Manifest-driven (papers.json): one venue-spanning report covering every
paper's full QN review (deep-research checklist, 5-voice panel,
quantum-CS fallacy report, Stage-6 CQE), with the token + real-USD
ledger, structured-telemetry summary, and a prominent AI-review
disclaimer.

Reuses the proven embedding helpers (markdown -> LaTeX with JSON
stripped and pipe tables converted to prose) from the two-paper
builder rather than duplicating them.
"""
from __future__ import annotations

import argparse
import datetime
import importlib.util
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
_TP = HERE.parent / "end_to_end" / "two_paper_novelty"
_spec = importlib.util.spec_from_file_location(
    "build_report", _TP / "build_report.py")
br = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(br)

latex_escape = br.latex_escape
fmt_int = br.fmt_int
fmt_cost = br.fmt_cost
collect_paper = br.collect_paper
md_to_latex_fragment = br.md_to_latex_fragment
_claude_cli_version = br._claude_cli_version

DISCLAIMER = (
    "These reviews are generated end-to-end by AI (the QuantumNovelty "
    "agent pipeline running on the Claude Code CLI). They are provided "
    "strictly for academic and demonstration purposes --- to show what "
    "the framework produces on real papers. We make NO claims about the "
    "correctness, quality, novelty, or publication-worthiness of the "
    "papers under review; four passed real peer review at their "
    "respective journals and one is a public arXiv preprint, and "
    "nothing here should be read as criticism of the authors or as a "
    "substitute for human peer review. Paper copyrights remain with "
    "their authors and publishers."
)

_NUMS = {1: "One", 2: "Two", 3: "Three", 4: "Four", 5: "Five",
         6: "Six", 7: "Seven", 8: "Eight", 9: "Nine", 10: "Ten"}


def render(manifest: dict, papers: list[dict]) -> str:
    L: list[str] = []

    def W(s: str = ""):
        L.append(s)

    W(r"\documentclass[10pt,letterpaper]{article}")
    W(r"\usepackage[margin=0.9in]{geometry}")
    W(r"\usepackage{booktabs}")
    W(r"\usepackage{amsmath,amssymb}")
    W(r"\usepackage{braket}")
    W(r"\usepackage{xcolor}")
    W(r"\usepackage{titlesec}")
    W(r"\usepackage{hyperref}")
    W(r"\usepackage{titling}")
    W(r"\usepackage{fancyhdr}")
    W(r"\usepackage{longtable}")
    W(r"\usepackage{calc}")
    W(r"\usepackage{array}")
    W(r"\usepackage{amssymb}")
    W(r"\usepackage{amsmath}")
    W(r"\usepackage[T1]{fontenc}")
    W(r"\providecommand{\tightlist}{\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}")
    W(r"\providecommand{\passthrough}[1]{#1}")
    W(r"\providecommand{\pandocbounded}[1]{#1}")
    W(r"\providecommand{\real}[1]{#1}")
    W(r"\definecolor{accent}{HTML}{1F3A8A}")
    W(r"\definecolor{muted}{HTML}{4A4D57}")
    W(r"\hypersetup{colorlinks=true, urlcolor=accent, linkcolor=accent}")
    W(r"\titleformat{\section}{\Large\bfseries\color{accent}}{\thesection}{0.6em}{}")
    W(r"\titleformat{\subsection}{\large\bfseries}{\thesubsection}{0.5em}{}")
    W(r"\titleformat{\subsubsection}{\normalsize\bfseries}{\thesubsubsection}{0.5em}{}")
    W(r"\setlength{\droptitle}{-3em}")
    W(r"\pagestyle{fancy}")
    W(r"\fancyhf{}")
    n = len(papers)
    num_word = _NUMS.get(n, str(n))
    plural = "papers" if n != 1 else "paper"
    W(rf"\rhead{{\footnotesize\color{{muted}}QuantumNovelty --- "
      rf"paper-audit ({n} {plural})}}")
    W(r"\lhead{\footnotesize\color{muted}\thepage}")
    W(r"\renewcommand{\headrulewidth}{0pt}")

    subtitle = manifest.get("title") or (
        f"{num_word} real quantum-computing {plural}")
    W(r"\title{\textbf{\Large QuantumNovelty Review Showcase}\\[0.4em]")
    W(rf"\large {latex_escape(subtitle)}}}")
    W(r"\author{Generated by the QuantumNovelty paper-audit pipeline}")
    W(rf"\date{{{datetime.date.today().strftime('%B %Y')}}}")
    W(r"\begin{document}")
    W(r"\maketitle")

    # ---------- provenance header ----------
    build_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M").strip()
    cli_ver = _claude_cli_version()
    models = sorted({s.get("model_id")
                     for p in papers for s in p["data"]["stages"]
                     if s.get("model_id")})
    W(r"\begin{center}")
    W(r"\renewcommand{\arraystretch}{1.25}")
    W(r"\begin{tabular}{ll}")
    W(r"\toprule")
    W(r"\textbf{Project} & QuantumNovelty (QN) --- audit-and-falsify "
      r"framework for quantum-computing research \\")
    W(r"\textbf{Repository} & "
      r"\url{https://github.com/boltzmannentropy/QuantumNovelty} \\")
    W(r"\textbf{Author} & Shlomo Kashani "
      r"(\href{https://qneura.ai/apps.html}{QNeura.ai}) \\")
    W(r"\textbf{LLM backend} & Claude Code CLI "
      rf"(\texttt{{{latex_escape(cli_ver)}}}) \\")
    if models:
        W(r"\textbf{Model snapshots used} & "
          + r" \newline ".join(
              rf"\texttt{{{latex_escape(m)}}}" for m in models)
          + r" \\")
    W(rf"\textbf{{Report generated}} & {latex_escape(build_date)} by "
      r"\texttt{build\_reviews.py} \\")
    W(r"\bottomrule")
    W(r"\end{tabular}")
    W(r"\end{center}")
    W()

    # ---------- disclaimer ----------
    W(r"\begin{center}")
    W(r"\fbox{\parbox{0.92\textwidth}{\small\textbf{Disclaimer.} "
      + latex_escape(DISCLAIMER).replace("---", "---") + r"}}")
    W(r"\end{center}")
    W()

    # ---------- papers under analysis ----------
    W(r"\section{Papers under review}")
    W(r"\begin{tabular}{lp{0.42\textwidth}ll}")
    W(r"\toprule")
    W(r"Tag & Paper & Venue & arXiv \\")
    W(r"\midrule")
    for p in papers:
        m = p["meta"]
        W(rf"\texttt{{{latex_escape(m['tag'])}}} & "
          rf"{latex_escape(m['title'])} "
          rf"\newline {{\small\color{{muted}}{latex_escape(m['authors'])}}} & "
          rf"{latex_escape(m['venue_display'])} & "
          rf"\href{{https://arxiv.org/abs/{m['arxiv']}}}{{{m['arxiv']}}} \\")
        W(r"\addlinespace")
    W(r"\bottomrule")
    W(r"\end{tabular}")
    W()
    if n > 1:
        W(r"\noindent The peer-reviewed papers cover every target venue in "
          r"QN's journal registry; \texttt{hwqml} and \texttt{qcnn} cover "
          r"quantum machine learning, and \texttt{majorana2} is the hardware "
          r"entry --- a preprint audited against the PRX Quantum rubric.")

    # ---------- token + cost ledger ----------
    W(r"\section{Token + cost ledger}")
    W(r"Every LLM call records the model snapshot ID, exact input/output "
      r"token counts, and USD cost from the Claude CLI's JSON envelope.")
    W()
    W(r"\begin{tabular}{llrrrr}")
    W(r"\toprule")
    W(r"Paper & Stage & Input tk & Output tk & Cost (\$) & Elapsed (s) \\")
    W(r"\midrule")
    grand = {"in": 0, "out": 0, "cost": 0.0, "t": 0.0}
    for p in papers:
        for s in p["data"]["stages"]:
            if s.get("missing"):
                W(rf"{latex_escape(p['meta']['tag'])} & "
                  rf"{latex_escape(s['label'])} & - & - & - & - \\")
                continue
            W(rf"{latex_escape(p['meta']['tag'])} & "
              rf"{latex_escape(s['label'])} & "
              rf"{fmt_int(s.get('input_tokens'))} & "
              rf"{fmt_int(s.get('output_tokens'))} & "
              rf"{fmt_cost(s.get('cost_usd'))} & "
              rf"{(s.get('elapsed_s') or 0):.1f} \\")
        t = p["data"]["totals"]
        grand["in"] += t["input_tokens"]; grand["out"] += t["output_tokens"]
        grand["cost"] += t["cost_usd"]; grand["t"] += t["elapsed_s"]
        W(rf"\textbf{{{latex_escape(p['meta']['tag'])} total}} & & "
          rf"\textbf{{{fmt_int(t['input_tokens'])}}} & "
          rf"\textbf{{{fmt_int(t['output_tokens'])}}} & "
          rf"\textbf{{{fmt_cost(t['cost_usd'])}}} & "
          rf"\textbf{{{t['elapsed_s']:.1f}}} \\")
        W(r"\midrule")
    W(rf"\textbf{{Grand total}} & & \textbf{{{fmt_int(grand['in'])}}} & "
      rf"\textbf{{{fmt_int(grand['out'])}}} & "
      rf"\textbf{{{fmt_cost(grand['cost'])}}} & "
      rf"\textbf{{{grand['t']:.1f}}} \\")
    W(r"\bottomrule")
    W(r"\end{tabular}")

    # ---------- verdict summary ----------
    W(r"\section{Verdict summary}")
    W(r"\begin{tabular}{lccc}")
    W(r"\toprule")
    W(r"Paper & Panel score & EIC verdict & CQE composite \\")
    W(r"\midrule")
    for p in papers:
        gate = p["data"].get("quality_gate") or {}
        cqe = p["data"].get("cqe") or {}
        score = gate.get("score_1_to_10")
        verdict = gate.get("verdict") or "-"
        W(rf"\texttt{{{latex_escape(p['meta']['tag'])}}} & "
          rf"{score if score is not None else '-'}/10 & "
          rf"{latex_escape(str(verdict))} & "
          rf"{cqe.get('composite', '-')}/100 \\")
    W(r"\bottomrule")
    W(r"\end{tabular}")
    W()
    W(r"\noindent Panel score is the mean of the five voices' "
      r"\emph{Verdict: N/10} scores; the EIC verdict comes from the "
      r"vote table; the CQE composite is the geometric mean of the "
      r"six process-quality dimensions.")

    # ---------- per-paper deep dives ----------
    for p in papers:
        m = p["meta"]
        W(r"\clearpage")
        W(rf"\section{{{latex_escape(m['tag'])} --- "
          rf"\emph{{{latex_escape(m['title'])}}}}}")
        W(rf"\noindent {latex_escape(m['authors'])} \quad "
          rf"\href{{https://arxiv.org/abs/{m['arxiv']}}}"
          rf"{{arXiv:{m['arxiv']}}} \quad {latex_escape(m['venue_display'])}")
        W()
        for s in p["data"]["stages"]:
            W(rf"\subsection{{{latex_escape(m['tag'])} --- "
              rf"{latex_escape(s['label'])}}}")
            if s.get("model_id"):
                W(rf"\noindent\textcolor{{muted}}{{\small Model: "
                  rf"\texttt{{{latex_escape(s['model_id'])}}} "
                  rf"\textperiodcentered\ "
                  rf"{fmt_int(s.get('output_tokens'))} output tokens "
                  rf"\textperiodcentered\ "
                  rf"{(s.get('elapsed_s') or 0):.1f}\,s}}")
                W()
            if s["primary_md"].is_file():
                W(md_to_latex_fragment(s["primary_md"]))
            else:
                W(r"\emph{(stage output missing)}")
            W()

    W(r"\vfill")
    W(r"\begin{center}\small\textcolor{muted}{Made with "
      r"$\heartsuit$ for creators everywhere. "
      r"\href{https://qneura.ai/apps.html}{QNeura.ai} "
      r"\textperiodcentered\ Shlomo Kashani}\end{center}")
    W(r"\end{document}")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifest", default=HERE / "papers.json", type=Path)
    ap.add_argument("--reviews-root", required=True, type=Path,
                    help="dir containing <tag>/ run outputs "
                         "(01_research_review/ ... 04_summary/)")
    ap.add_argument("--out", default=HERE / "REVIEWS.tex", type=Path)
    args = ap.parse_args()

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    papers = []
    for m in manifest["papers"]:
        d = collect_paper(args.reviews_root / m["tag"])
        # quality gate lives next to the panel
        qg = args.reviews_root / m["tag"] / "02_reviewer_panel" / "_quality_gate.json"
        d["quality_gate"] = (json.loads(qg.read_text(encoding="utf-8"))
                             if qg.is_file() else {})
        papers.append({"meta": m, "data": d})

    args.out.write_text(render(manifest, papers), encoding="utf-8")
    print(f"wrote {args.out} ({args.out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
