"""Quantum-library selector for code generation.

Skills that emit executable ansatz / circuit / simulator code read the user's
`--quantum-lib` choice from here. Provides a uniform interface so the
code-generating skills don't hardcode library-specific idioms.

Supported libraries:
  qiskit       IBM Qiskit (qiskit-terra + qiskit-aer)
  pennylane    Xanadu PennyLane (autodiff + multi-backend)
  qutip        QuTiP (open-quantum-systems-focused; statevector + master eq.)
  mlxq         mlxq (Apple Silicon MLX-native statevector simulator;
                    the simulator used in the framework's motivating study)
  cirq         Google Cirq
  openfermion  OpenFermion (chemistry-Hamiltonian builder; usually paired
               with a simulator, not a simulator itself)
  no-code      User opted out of code generation (analytical paper only)

Each library entry provides:
  - import_lines       canonical imports for a skeleton ansatz file
  - ansatz_template    a placeholder Python ansatz the LLM will fill in
  - evaluator_call     how to evaluate <psi|H|psi> in this library
  - install_hint       pip install command
  - notes              library-specific gotchas (precision, default backends)
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass
class QuantumLibrary:
    name: str
    slug: str
    install_hint: str
    import_lines: str
    ansatz_template: str
    evaluator_call: str
    notes: str

    def code_skeleton(self, ansatz_body: str = "    pass",
                      n_qubits: int = 4) -> str:
        """Render a complete code skeleton for this library."""
        return (
            f"#!/usr/bin/env python3\n"
            f'"""Generated by QuantumNovelty for library: {self.name}."""\n'
            f"{self.import_lines}\n\n"
            f"def build_ansatz(params):\n"
            f"    \"\"\"Return the ansatz circuit for {n_qubits} qubits.\"\"\"\n"
            f"{ansatz_body}\n\n"
            f"def evaluate(params, hamiltonian):\n"
            f"    \"\"\"Compute <psi|H|psi>.\"\"\"\n"
            f"    {self.evaluator_call}\n"
        )


_LIBS: dict[str, QuantumLibrary] = {}


def _register(lib: QuantumLibrary) -> None:
    _LIBS[lib.slug] = lib


_register(QuantumLibrary(
    name="Qiskit",
    slug="qiskit",
    install_hint="pip install qiskit qiskit-aer qiskit-nature",
    import_lines=(
        "import numpy as np\n"
        "from qiskit import QuantumCircuit\n"
        "from qiskit.quantum_info import Statevector, SparsePauliOp"
    ),
    ansatz_template=(
        "    qc = QuantumCircuit(N_QUBITS)\n"
        "    # ... LLM-generated gates here ...\n"
        "    return qc"
    ),
    evaluator_call=(
        "psi = Statevector.from_instruction(build_ansatz(params))\n"
        "    return float(psi.expectation_value(hamiltonian).real)"
    ),
    notes=(
        "Default backend is statevector. For shot-based runs use AerSimulator. "
        "qiskit-nature provides Hamiltonian builders (UCCSD, ADAPT-VQE, etc.). "
        "Pin qiskit>=1.0 — pre-1.0 APIs (QuantumInstance, qiskit-terra split) "
        "are deprecated."
    ),
))

_register(QuantumLibrary(
    name="PennyLane",
    slug="pennylane",
    install_hint="pip install pennylane",
    import_lines=(
        "import numpy as np\n"
        "import pennylane as qml"
    ),
    ansatz_template=(
        "    dev = qml.device(\"default.qubit\", wires=N_QUBITS)\n\n"
        "    @qml.qnode(dev)\n"
        "    def circuit(params):\n"
        "        # ... LLM-generated gates here ...\n"
        "        return qml.expval(HAMILTONIAN)\n"
        "    return circuit"
    ),
    evaluator_call=(
        "circuit = build_ansatz(params)\n"
        "    return float(circuit(params))"
    ),
    notes=(
        "QNodes return expectation values directly via qml.expval — no "
        "manual <psi|H|psi> calculation needed. Autodiff via interfaces "
        "(JAX/PyTorch/TF). For chemistry use pennylane.qchem.molecular_hamiltonian."
    ),
))

_register(QuantumLibrary(
    name="QuTiP",
    slug="qutip",
    install_hint="pip install qutip",
    import_lines=(
        "import numpy as np\n"
        "from qutip import basis, tensor, sigmax, sigmay, sigmaz, qeye, expect"
    ),
    ansatz_template=(
        "    # Construct |psi> = U(params)|0...0>\n"
        "    psi0 = tensor([basis(2, 0) for _ in range(N_QUBITS)])\n"
        "    # ... LLM-generated U(params) here ...\n"
        "    return psi"
    ),
    evaluator_call=(
        "psi = build_ansatz(params)\n"
        "    return float(expect(hamiltonian, psi).real)"
    ),
    notes=(
        "Excellent for open-quantum-systems work (Lindblad / master equation). "
        "Statevector ops via tensor products; slower than dedicated simulators "
        "for large N. Good interop with scipy."
    ),
))

_register(QuantumLibrary(
    name="mlxq",
    slug="mlxq",
    install_hint=(
        "pip install -e <path-to-mlxq>  "
        "# Apple Silicon native; install from local clone"
    ),
    import_lines=(
        "import mlx.core as mx\n"
        "from mlxq import Circuit, statevector_expectation"
    ),
    ansatz_template=(
        "    circuit = Circuit(N_QUBITS, backend=\"mlx\")\n"
        "    # ... LLM-generated gates here ...\n"
        "    return circuit"
    ),
    evaluator_call=(
        "circuit = build_ansatz(params)\n"
        "    return float(statevector_expectation(circuit, hamiltonian))"
    ),
    notes=(
        "Apple Silicon MLX-native statevector simulator. Used in the "
        "motivating study. Default precision is complex64 for speed; pass "
        "dtype=mx.complex128 explicitly for published energy comparisons "
        "(a silent complex64 default once cost us a precision floor)."
    ),
))

_register(QuantumLibrary(
    name="Cirq",
    slug="cirq",
    install_hint="pip install cirq",
    import_lines=(
        "import numpy as np\n"
        "import cirq"
    ),
    ansatz_template=(
        "    qubits = cirq.LineQubit.range(N_QUBITS)\n"
        "    circuit = cirq.Circuit()\n"
        "    # ... LLM-generated gates here ...\n"
        "    return circuit, qubits"
    ),
    evaluator_call=(
        "circuit, qubits = build_ansatz(params)\n"
        "    psi = cirq.final_state_vector(circuit)\n"
        "    return float(np.real(np.conj(psi) @ hamiltonian @ psi))"
    ),
    notes=(
        "Google Cirq. LineQubit for VQE, GridQubit for hardware-aware. "
        "TFQ for differentiable; openfermion-cirq bridge for chemistry."
    ),
))

_register(QuantumLibrary(
    name="OpenFermion",
    slug="openfermion",
    install_hint="pip install openfermion openfermionpyscf",
    import_lines=(
        "import numpy as np\n"
        "from openfermion import MolecularData, get_molecular_hamiltonian"
    ),
    ansatz_template=(
        "    # OpenFermion is a Hamiltonian builder, not a circuit simulator.\n"
        "    # Pair with one of the simulator libraries above for evaluation.\n"
        "    pass"
    ),
    evaluator_call=(
        "raise NotImplementedError(\n"
        "        \"OpenFermion builds Hamiltonians; pair with qiskit/pennylane/\"\n"
        "        \"mlxq/cirq/qutip for evaluation. Pick a simulator backend.\"\n"
        "    )"
    ),
    notes=(
        "Chemistry-Hamiltonian builder (UCCSD, JW/BK mappings, active space "
        "transforms). Modern API: MolecularData.get_molecular_hamiltonian("
        "occupied_indices, active_indices). The deprecated "
        "chem.active_space_transform was removed in openfermion >= 1.5."
    ),
))

_register(QuantumLibrary(
    name="No code (analytical paper only)",
    slug="no-code",
    install_hint="N/A",
    import_lines="# No code generation requested.",
    ansatz_template="    pass  # No code generation",
    evaluator_call="pass  # No code generation",
    notes=(
        "User opted out of code generation. The paper-drafter and reviewer "
        "skills will still produce text outputs but will not emit executable "
        "code; the audit pipeline will not attempt to re-run experiments."
    ),
))


# =========================================================================
# Public API
# =========================================================================

def known_libraries() -> list[str]:
    return sorted(_LIBS)


def library(slug: str) -> QuantumLibrary:
    try:
        return _LIBS[slug]
    except KeyError:
        raise KeyError(
            f"unknown quantum library {slug!r}; known: "
            f"{', '.join(known_libraries())}"
        )


# =========================================================================
# CLI
# =========================================================================

if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("list", help="print all known library slugs")
    show = sub.add_parser("show", help="print a library's notes + install hint")
    show.add_argument("slug")
    skel = sub.add_parser("skeleton", help="emit a code skeleton for a library")
    skel.add_argument("slug")
    skel.add_argument("--n-qubits", type=int, default=4)
    args = ap.parse_args()
    if args.cmd == "list":
        for slug in known_libraries():
            print(f"{slug:14} {library(slug).name}")
    elif args.cmd == "show":
        lib = library(args.slug)
        print(f"# {lib.name} ({lib.slug})\n")
        print(f"**Install:** `{lib.install_hint}`\n")
        print(f"**Notes:** {lib.notes}\n")
    elif args.cmd == "skeleton":
        print(library(args.slug).code_skeleton())
